# Generated by Django 3.2.9 on 2021-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.IntegerField()),
                ('ItemName', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
    ]
